name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build
        run: |
          mkdir build && cd build
          cmake ..
          cmake --build .
          cd test
          ctest -C Debug

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: |
            build

  build-macos:
    runs-on: macos-latest

    continue-on-error: true # macOS support is still WIP

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install dependencies and build
        run: |
          brew install doxygen
          mkdir build && cd build
          cmake ..
          cmake --build .
          #cd test
          #ctest -C Debug

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: macos-build
          path: |
            build

  build-linux:
    runs-on: ubuntu-latest

    continue-on-error: true # Linux support is still WIP

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install dependencies and build
        run: |
          sudo apt-get install doxygen=1.9.3 libx11-dev libxtst-dev -y
          mkdir build && cd build
          cmake ..
          cmake --build .
          cd test
          ctest -C Debug

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux-build
          path: |
            build
