name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - run: |
          mkdir build && cd build
          cmake ..
          cmake --build .
          cd test
          ctest -C Debug

      - uses: actions/upload-artifact@v3
        name: Windows build
        with:
          name: windows-build
          path: |
            build

  build-macos:
    runs-on: macos-latest

    continue-on-error: true # macOS support is still WIP

    steps:
      - uses: actions/checkout@v3
      - run: |
          brew install doxygen
          mkdir build && cd build
          cmake ..
          cmake --build .
          #cd test
          #ctest -C Debug

      - uses: actions/upload-artifact@v3
        name: macOS build
        with:
          name: macos-build
          path: |
            build

  build-linux:
    runs-on: ubuntu-latest

    continue-on-error: true # Linux support is still WIP

    steps:
      - uses: actions/checkout@v3
      - run: |
          sudo apt-get install doxygen libx11-dev libxtst-dev -y
          mkdir build && cd build
          cmake ..
          cmake --build .
          cd test
          ctest -C Debug

      - uses: actions/upload-artifact@v3
        name: Linux build
        with:
          name: linux-build
          path: |
            build
